FROM registry.redhat.io/openshift4/jenkins-agent-nodejs-12-rhel7

USER root

ENV SONARQUBE_SCANNER_VERSION=4.4.2.1543 \
    HOME=/home/jenkins 

# Install .NET sdk rpm
RUN rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm

# Install headless Java and .NET sdk
RUN yum install dotnet-sdk-3.1 -y

WORKDIR /

# Install SonarQube Scanner as the running user
RUN dotnet tool install --global dotnet-sonarscanner
ENV PATH="${PATH}:$HOME/.dotnet/tools"

RUN chown -R 1029:0 /usr/local/bin && \
    chown -R 1029:0 $HOME && \
    chmod -R g+rwx $HOME

USER 1029
